# See https://faun.pub/import-the-docker-compose-file-into-another-compose-file-4865d7fa0fd4
# See https://stackoverflow.com/questions/55650342/import-docker-compose-file-in-another-compose-file/76678762#76678762

include:
  - shared/docker-compose.yaml
  - docker-compose.prod.yaml

services:
  webapp:
    depends_on:
      - redis